version: '2'
services:
 web:
   image: springboot-docker-compose-demo
   ports: 
       - 8080
   networks:
       - front-tier
       - back-tier
 db:
    container_name: sample_db
    image: postgres
    links: 
       - web
    volumes:
        - sample_db:/var/lib/postgresql/data
    environment:
        - POSTGRES_PASSWORD=admin123
        - POSTGRES_USER=postgres
        - POSTGRES_DB=sample
        - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
        - 5432:5432
    networks:
       - back-tier
 lb:
    image: dockercloud/haproxy
    ports:
        - 80:80
    links:
        - web
    networks:
        - front-tier
        - back-tier
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock 
networks:
    front-tier:
      driver: bridge
    back-tier:
      driver: bridge            
       
volumes:
    sample_db: {}
